### PR TITLE
Add support for embedded fields

### PR DESCRIPTION
**Pull request by bjornvanspengen**

### CODE REVIEW

**Review by toland — APPROVED** [review]
LGTM

**Comment by bernardd** [comment]
Hey @bjornvanspengen - thanks heaps for the PR. My only comment would be that it doesn't seem to handle nested embeds - would there be a neat way to add that?

**Comment by bjornvanspengen** [comment]
> Hey @bjornvanspengen - thanks heaps for the PR. My only comment would be that it doesn't seem to handle nested embeds - would there be a neat way to add that?

Hey @bernardd - It actually does handle nested embeds. cast_embed/3 uses the changeset/2 function of the embedded module by default. Casting the nested embed within the changeset function  will make it work. I added a nested embed to the test data.

**Comment by bernardd** [comment]
Ah cool, thanks - that explains what I was doing wrong when I tested it. Thanks very much!

**Review by bernardd — APPROVED** [review]

**Pull request merged**
