### PR TITLE
Enable Postgrex's notification reconnection

### PR DESCRIPTION
**Pull request by bernardd**

### CODE REVIEW

**Comment by toland** [comment]
I'm going to hold off on merging this because we can't release it on Hex with a Github dependency. It's better to wait for the Postgrex package to be updated.

**Comment by toland** [comment]
We could merge this on a branch if you want to import it into Wocky before Postgrex is updated.

**Comment by bernardd** [comment]
It's fine - the only reason I wanted it in sooner rather than later was to avoid having to do manual restarts after DB server updates. We'll just have to remember to keep doing them for now.

**Comment by bernardd** [comment]
Postgrex 0.15.3 is in hex now so I'm going to go ahead and merge this

**Pull request merged**
